stages:
  - deploy

deploy:
  stage: deploy
  image: ${BUILDER_PATH} 
  tags:
    - docker
  script: 
    - python3 setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - /v.*/

