stages:
  - deploy

deploy:
  stage: deploy
  image: registry.devops.ukfast.co.uk/tom.couser/python-wheel:latest
  tags:
    - docker
  script: 
    - python3 setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - /v.*/

